# Generated by Django 4.0.5 on 2022-08-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('price', models.FloatField(default=30.3)),
                ('length', models.DecimalField(decimal_places=1, default=30.3, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, default=30.3, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=1, default=30.3, max_digits=5)),
                ('paper', models.CharField(max_length=90)),
                ('coating', models.CharField(max_length=90)),
                ('printed_sides', models.CharField(max_length=90)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.category')),
            ],
        ),
    ]
