# Generated by Django 2.2.8 on 2022-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.ManyToManyField(to='product_app.Variant_type'),
        ),
    ]
