# Generated by Django 4.1 on 2022-08-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant_type',
            new_name='VariantType',
        ),
    ]
