# Generated by Django 4.1 on 2022-08-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
    ]
