# Generated by Django 4.1 on 2022-08-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_rename_variant_type_varianttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='variant_type_name',
            new_name='variant_type',
        ),
    ]
