# Generated by Django 2.2.8 on 2022-08-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20220824_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.Variant_type'),
            preserve_default=False,
        ),
    ]
