# Generated by Django 4.1 on 2022-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_price_type_id_alter_price_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
