# Generated by Django 4.1 on 2022-08-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_rename_variant_type_name_productattribute_variant_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantType',
            new_name='Variant_type',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='variant_type',
            new_name='variant_type_name',
        ),
    ]
