# Generated by Django 2.2.8 on 2022-08-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20220824_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.ManyToManyField(to='product_app.Variant_type'),
        ),
    ]
