# Generated by Django 4.1 on 2022-08-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productattribute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='total_variant_price',
        ),
        migrations.AddField(
            model_name='totalprice',
            name='total_variant_price',
            field=models.IntegerField(default=1, verbose_name='total_variant_price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='type_id',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totalprice',
            name='cost_per_delivery',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totalprice',
            name='cost_per_product',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totalprice',
            name='tax',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totalprice',
            name='total_cost',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
