# Generated by Django 2.2.8 on 2022-08-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20220826_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='element_name',
            new_name='element',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='ft',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
        migrations.AddField(
            model_name='variant',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.Elements'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='unit',
            field=models.FloatField(default=0),
        ),
    ]
