# Generated by Django 4.1 on 2022-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='total_price',
            field=models.FloatField(default=1, verbose_name='total_price'),
            preserve_default=False,
        ),
    ]
