# Generated by Django 2.2.8 on 2022-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20220826_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='field_type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
