# Generated by Django 2.2.8 on 2022-09-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_variant_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='width',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Width',
        ),
    ]
