# Generated by Django 2.2.8 on 2022-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20220824_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant_type',
            name='variant_type_name',
            field=models.CharField(max_length=90),
        ),
    ]
