# Generated by Django 4.1 on 2022-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_price_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_delivery', models.FloatField(verbose_name='cost_per_delivery')),
                ('cost_per_product', models.FloatField(verbose_name='cost_per_product')),
                ('tax', models.FloatField(verbose_name='tax')),
                ('total_cost', models.FloatField(verbose_name='total_cost')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='total',
        ),
        migrations.RemoveField(
            model_name='price',
            name='total_price',
        ),
        migrations.AddField(
            model_name='price',
            name='variant_price',
            field=models.FloatField(default=1, verbose_name='variant_price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
