# Generated by Django 4.1 on 2022-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_total_price_remove_price_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_price',
            name='cost_per_delivery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_price',
            name='cost_per_product',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='total_price',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
