# Generated by Django 4.1 on 2022-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_total_price_cost_per_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_price',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
