# Generated by Django 4.1 on 2022-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_remove_price_total_variant_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='variant_price',
            field=models.FloatField(blank=True),
        ),
    ]
