# Generated by Django 4.1 on 2022-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_total_price_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='total_variant_price',
            field=models.FloatField(default=1, verbose_name='total_variant_price'),
            preserve_default=False,
        ),
    ]
