# Generated by Django 4.1 on 2022-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_alter_price_total_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='total_variant_price',
            field=models.IntegerField(verbose_name='total_variant_price'),
        ),
    ]
