# Generated by Django 4.1 on 2022-08-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_remove_price_total_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='total_variant_price',
            field=models.IntegerField(default=1, verbose_name='total_variant_price'),
            preserve_default=False,
        ),
    ]
