# Generated by Django 4.0.5 on 2022-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_contact_number',
            field=models.IntegerField(default=91),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(default=91),
        ),
    ]
