# Generated by Django 4.0.5 on 2022-08-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_user_address_user_alternative_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alternative_contact_number',
            field=models.CharField(default=91, max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default=91, max_length=12),
        ),
    ]
