# Generated by Django 4.0.5 on 2022-08-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_user_is_verified_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
