# Generated by Django 4.0.5 on 2022-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_user_alternative_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alternative_contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
