# Generated by Django 2.2.8 on 2022-09-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='stripe_Product',
        ),
    ]
