# Generated by Django 4.1.2 on 2022-10-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
