# Generated by Django 4.1.2 on 2022-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_app', '0002_alter_banner_button_text_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(),
        ),
    ]
