# Generated by Django 4.1.2 on 2022-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_app', '0003_alter_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=350)),
                ('heading', models.CharField(max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
