# Generated by Django 4.1.2 on 2022-10-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_app', '0004_headingcategory_headings_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headings',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel_app.headingcategory'),
        ),
    ]
